on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint shell script
        uses: azohra/shell-linter@v0.4.0
        with:
          path: "setup-wrangler.sh"
          
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - run: wrangler --help

  test-on-linux-input-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: ./
      with:
        wrangler_version: '1.6.0'
    - run: wrangler --help

  test-on-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - run: wrangler --help

  compare-with-wrangler-action:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: 'xxx'
          publish: false
          preCommands: wrangler --help
